### ISSUE TITLE
Parallel Running causes contention on temp extraction folder

### ISSUE THREAD

**Issue by leparduk** [andrewrdavidson/powershell-quality-checks#6]
When running in an Azure DevOps pipeline with a triggered or scheduled build against two branches it was noticed that one build was removing files from the temp extraction folder while another was running tests.
We should introduce a random element into the path, i.e. a `guid` or `h:m:s:milli`.

**Comment by andrewrdavidson** [comment]
Yes, was never designed for that. Only issue with the GUID option (which is my preferred route) is passing through the system so that the extraction and tests look in the correct place.

**Comment by andrewrdavidson** [comment]
Will look at a fix for that soon, unless you want to fix and PR @leparduk ?

**Comment by andrewrdavidson** [comment]
Fixed in #7
